== Uninstalling

Parts of the operator must be manually uninstalled for security purposes. It also allows you to save cluster resources,
    as terminals cannot be idled when the operator is uninstalled. In order to fully uninstall an admin must:

    . Ensure that all DevWorkspace Custom Resources are removed along with their related k8s objects, like deployments.
       It is crucial that this is done first, otherwise finalizers might make it difficult to fully uninstall the operator.

    kubectl delete devworkspaces.workspace.devfile.io --all-namespaces --all --wait
    kubectl delete workspaceroutings.controller.devfile.io --all-namespaces --all --wait
    kubectl delete components.controller.devfile.io --all-namespaces --all --wait

    . Uninstall the Operator
    . Remove the custom resource definitions

    kubectl delete customresourcedefinitions.apiextensions.k8s.io workspaceroutings.controller.devfile.io
    kubectl delete customresourcedefinitions.apiextensions.k8s.io components.controller.devfile.io
    kubectl delete customresourcedefinitions.apiextensions.k8s.io devworkspaces.workspace.devfile.io

    . Remove DevWorkspace Webhook Server Deployment itself

    kubectl delete deployment/devworkspace-webhook-server -n openshift-operators

    . Remove lingering service, secrets, and configmaps

    kubectl delete all --selector app.kubernetes.io/part-of=devworkspace-operator,app.kubernetes.io/name=devworkspace-webhook-server
    kubectl delete serviceaccounts devworkspace-webhook-server -n openshift-operators
    kubectl delete configmap devworkspace-controller -n openshift-operators
    kubectl delete clusterrole devworkspace-webhook-server
    kubectl delete clusterrolebinding devworkspace-webhook-server

    . Remove mutating/validating webhook configurations. _note:_ there may be a few seconds where you cannot exec into
       pods between steps 4 and 6. This is expected. Once you remove the webhooks you will be able to exec into pods again.

    kubectl delete mutatingwebhookconfigurations controller.devfile.io
    kubectl delete validatingwebhookconfigurations controller.devfile.io
