apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-web-terminal-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/che-incubator/che-workspace-operator-index:latest
  publisher: Red Hat
  displayName: Web Terminal Operator Catalog
