apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: web-terminal
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: web-terminal
  source: custom-web-terminal-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: web-terminal.v1.3.0
