apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: web-terminal
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: web-terminal
  source: web-terminal-crd-registry
  sourceNamespace: openshift-marketplace
  startingCSV: web-terminal.v1.0.0
