---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: edit-workspaces
rules:
  - apiGroups:
      - workspace.devfile.io
    resources:
      - devworkspaces
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - controller.devfile.io
    resources:
      - workspaceroutings
      - components
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
