apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: web-terminal-controller-clusterrole
  labels:
    app.kubernetes.io/name: web-terminal-controller
    app.kubernetes.io/part-of: web-terminal-operator
rules:
  - apiGroups:
      - workspace.devfile.io
    resources:
      - devworkspacetemplates
    verbs:
      - '*'
