#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Next Dockerimages

on:
  push:
    branches: [ master ]

jobs:

  build-next-imgs:
    runs-on: ubuntu-latest
    env:
      BUNDLE_IMG: quay.io/wto/web-terminal-operator-metadata:next
      INDEX_IMG: quay.io/wto/web-terminal-operator-index:next
      OPM_VERSION: v1.13.1
    steps:
    - name: Install Operator SDK
      uses: shivanshs9/setup-k8s-operator-sdk@v1
      with:
        version: "^0.17.0"

    - name: Cache OPM ${{ env.OPM_VERSION }}
      uses: actions/cache@v2
      id: cache-opm
      with:
        path: ~/cache
        key: opm-${{ env.OPM_VERSION }}

    - name: Download OPM ${{ env.OPM_VERSION }}
      if: steps.cache-opm.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/cache
        wget https://github.com/operator-framework/operator-registry/releases/download/${OPM_VERSION}/linux-amd64-opm -O ~/cache/opm${OPM_VERSION} > /dev/null
        #${OPM_VERSION} is used in binary name to prevent caching after upgrading
        chmod +x ~/cache/opm${OPM_VERSION}
    - name: Install OPM ${{ env.OPM_VERSION }}
      run: |
        mkdir -p ~/bin
        cp ~/cache/opm${OPM_VERSION} ~/bin/opm
        echo "::add-path::$HOME/bin"

    - name: Checkout web-terminal-operator source code
      uses: actions/checkout@v2

    - name: "Docker Quay.io Login with WTO Robot"
      env:
        DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin quay.io

    - name: "Build Bundle & Index images"
      run: make build

    - name: "Docker Logout"
      run: docker logout
