#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:

  check-wto-controller:
    name: Check WTO controller image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout web-terminal-operator source code
      uses: actions/checkout@v2

    - name: "Check WTO Controller image"
      run: docker build -t wto-controller:test -f build/dockerfiles/controller.Dockerfile .
